// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    // Activity
    [Table("Activity", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Activity: BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ActivityID", Order = 1, TypeName = "int")]
        [Index(@"PK_Activity", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Activity ID")]
        public int ActivityId { get; set; } // ActivityID (Primary key)

        [Column(@"ActivityAction", Order = 2, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Activity action")]
        public string ActivityAction { get; set; } // ActivityAction (length: 50)

        [Column(@"ActivityTypeID", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Activity type ID")]
        public int ActivityTypeId { get; set; } // ActivityTypeID

        [Column(@"ActivityAffecterUserID", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Activity affecter user ID")]
        public int ActivityAffecterUserId { get; set; } // ActivityAffecterUserID

        [Column(@"UpdatedBy", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        // Foreign keys
        [JsonIgnore]
        [ForeignKey("CreatedBy")] public virtual Person Person_CreatedBy { get; set; } // FK_Activity_Person
        [JsonIgnore]
        [ForeignKey("UpdatedBy")] public virtual Person Person_UpdatedBy { get; set; } // FK_Activity_Person1

        public Activity()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
