// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // CVBank
    [Table("CVBank", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class CvBank
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"CVBankID", Order = 1, TypeName = "int")]
        [Index(@"PK_CVBank", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Cvb ank ID")]
        public int CvBankId { get; set; } // CVBankID (Primary key)

        [Column(@"CVBankText", Order = 2, TypeName = "varchar(max)")]
        [Display(Name = "Cvb ank text")]
        public string CvBankText { get; set; } // CVBankText

        [Column(@"CVBankUniqueID", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Cvb ank unique ID")]
        public string CvBankUniqueId { get; set; } // CVBankUniqueID (length: 50)

        [Column(@"CVBankFilename", Order = 4, TypeName = "varchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Cvb ank filename")]
        public string CvBankFilename { get; set; } // CVBankFilename (length: 100)

        [Column(@"UpdatedBy", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CvBankOwner> CvBankOwners { get; set; } // CVBankOwner.FK_CVBankOwner_CVBank

        public CvBank()
        {
            CvBankOwners = new System.Collections.Generic.List<CvBankOwner>();
        }
    }

}
// </auto-generated>
