// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using System.ComponentModel.DataAnnotations;

    // Dictionary
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class DictionaryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Dictionary>
    {
        public DictionaryConfiguration()
            : this("dbo")
        {
        }

        public DictionaryConfiguration(string schema)
        {
            Property(x => x.DictionaryType).IsUnicode(false);
            Property(x => x.Id2).IsOptional();
            Property(x => x.Id3).IsOptional();
            Property(x => x.Description).IsOptional().IsUnicode(false);
            Property(x => x.FullDescription).IsOptional().IsUnicode(false);
            Property(x => x.Hierarchy).IsOptional();
            Property(x => x.DepartmentId).IsOptional();
            Property(x => x.CompanyId).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.UpdatedBy).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.DateAdded).IsOptional();
            Property(x => x.DateUpdated).IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
