// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository;
    using entityframeworkrepository.core.entity;
    using Newtonsoft.Json;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    // Event
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class EventConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Event>
    {
        public EventConfiguration()
            : this("dbo")
        {
        }

        public EventConfiguration(string schema)
        {
            Property(x => x.JobFormResultId).IsOptional();
            Property(x => x.EventNote).IsOptional().IsUnicode(false);
            Property(x => x.EventTypeId).IsOptional();
            Property(x => x.EventStartDate).IsOptional();
            Property(x => x.EventEndDate).IsOptional();
            Property(x => x.EventAttendee).IsOptional();
            Property(x => x.UpdatedBy).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.DateAdded).IsOptional();
            Property(x => x.DateUpdated).IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
