// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // InterviewKit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class InterviewKitConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<InterviewKit>
    {
        public InterviewKitConfiguration()
            : this("dbo")
        {
        }

        public InterviewKitConfiguration(string schema)
        {
            Property(x => x.InterviewKitTypeId).IsOptional();
            Property(x => x.InterviewKitTitle).IsOptional().IsUnicode(false);
            Property(x => x.InterviewKitRequirement).IsOptional().IsUnicode(false);
            Property(x => x.InterviewQuestions).IsOptional().IsUnicode(false);
            Property(x => x.JobId).IsOptional();
        }
    }

}
// </auto-generated>
