// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // JobBoard
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class JobBoardConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<JobBoard>
    {
        public JobBoardConfiguration()
            : this("dbo")
        {
        }

        public JobBoardConfiguration(string schema)
        {
            Property(x => x.JobBoardName).IsUnicode(false);
            Property(x => x.JobBoardLogo).IsUnicode(false);
            Property(x => x.JobBoardDescription).IsOptional().IsUnicode(false);
        }
    }

}
// </auto-generated>
