// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // JobBoardCart
    [Table("JobBoardCart", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class JobBoardCart
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"JobBoardCartID", Order = 1, TypeName = "int")]
        [Index(@"PK_JobBoardCart", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Job board cart ID")]
        public int JobBoardCartId { get; set; } // JobBoardCartID (Primary key)

        [Column(@"JobID", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Job ID")]
        public int JobId { get; set; } // JobID

        [Column(@"JobBoardID", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Job board ID")]
        public int JobBoardId { get; set; } // JobBoardID

        [Column(@"UpdatedBy", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 6, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated
    }

}
// </auto-generated>
