// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository;
    using entityframeworkrepository.core.entity;
    using Newtonsoft.Json;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    // Job
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class JobConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Job>
    {
        public JobConfiguration()
            : this("dbo")
        {
        }

        public JobConfiguration(string schema)
        {
            Property(x => x.JobCode).IsOptional().IsUnicode(false);
            Property(x => x.JobTitle).IsOptional().IsUnicode(false);
            Property(x => x.JobDescription).IsOptional().IsUnicode(false);
            Property(x => x.JobDepartment).IsOptional().IsUnicode(false);
            Property(x => x.JobStatusId).IsOptional();
            Property(x => x.CountryId).IsOptional();
            Property(x => x.City).IsOptional().IsUnicode(false);
            Property(x => x.IsRemoteJob).IsOptional();
            Property(x => x.JobRequirement).IsOptional().IsUnicode(false);
            Property(x => x.JobBenefit).IsOptional().IsUnicode(false);
            Property(x => x.InHouseOrAgency).IsOptional();
            Property(x => x.EmploymentTypeId).IsOptional();
            Property(x => x.ExperienceId).IsOptional();
            Property(x => x.Education).IsOptional();
            Property(x => x.JobKeywords).IsOptional().IsUnicode(false);
            Property(x => x.SalaryFrom).IsOptional();
            Property(x => x.SalaryTo).IsOptional();
            Property(x => x.CurrencyId).IsOptional();
            Property(x => x.PersonId).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.IsVisible).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
