// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    // JobFormResult
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class JobFormResultConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<JobFormResult>
    {
        public JobFormResultConfiguration()
            : this("dbo")
        {
        }

        public JobFormResultConfiguration(string schema)
        {
            Property(x => x.JobFormId).IsOptional();
            Property(x => x.CandidateId).IsOptional();
            Property(x => x.FirstName).IsOptional().IsUnicode(false);
            Property(x => x.LastName).IsOptional().IsUnicode(false);
            Property(x => x.Email).IsOptional().IsUnicode(false);
            Property(x => x.Headline).IsOptional().IsUnicode(false);
            Property(x => x.Telephone).IsOptional().IsUnicode(false);
            Property(x => x.Address).IsOptional().IsUnicode(false);
            Property(x => x.Photo).IsOptional().IsUnicode(false);
            Property(x => x.Video).IsOptional().IsUnicode(false);
            Property(x => x.Summary).IsOptional().IsUnicode(false);
            Property(x => x.CvBankId).IsOptional();
            Property(x => x.Source).IsOptional().IsUnicode(false);
            Property(x => x.Referer).IsUnicode(false);
            Property(x => x.IsRead).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.AdminBlock).IsOptional();
            Property(x => x.IsCoverLetterIncluded).IsOptional();
            Property(x => x.QuestionAnswerXml).IsOptional().IsUnicode(false);
            Property(x => x.UpdatedBy).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.DateAdded).IsOptional();
            Property(x => x.DateUpdated).IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
