// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // JobFormResultX
    [Table("JobFormResultX", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class JobFormResultX
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"JobFormResultID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Job form result ID")]
        public int JobFormResultId { get; set; } // JobFormResultID (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"JobFormID", Order = 2, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Job form ID")]
        public int JobFormId { get; set; } // JobFormID (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CandidateID", Order = 3, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Candidate ID")]
        public int CandidateId { get; set; } // CandidateID (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"FirstName", Order = 4, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "First name")]
        public string FirstName { get; set; } // FirstName (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LastName", Order = 5, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Last name")]
        public string LastName { get; set; } // LastName (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Email", Order = 6, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Headline", Order = 7, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Headline")]
        public string Headline { get; set; } // Headline (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Telephone", Order = 8, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Phone]
        [Display(Name = "Telephone")]
        public string Telephone { get; set; } // Telephone (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Address", Order = 9, TypeName = "varchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Address")]
        public string Address { get; set; } // Address (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Photo", Order = 10, TypeName = "varchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Key]
        [Display(Name = "Photo")]
        public string Photo { get; set; } // Photo (Primary key) (length: 100)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Video", Order = 11, TypeName = "varchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Key]
        [Display(Name = "Video")]
        public string Video { get; set; } // Video (Primary key) (length: 100)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Summary", Order = 12, TypeName = "varchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Key]
        [Display(Name = "Summary")]
        public string Summary { get; set; } // Summary (Primary key) (length: 200)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CVBankID", Order = 13, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Cvb ank ID")]
        public int CvBankId { get; set; } // CVBankID (Primary key)

        [Column(@"Source", Order = 14, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Source")]
        public string Source { get; set; } // Source (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Referer", Order = 15, TypeName = "varchar")]
        [Required]
        [MaxLength(150)]
        [StringLength(150)]
        [Key]
        [Display(Name = "Referer")]
        public string Referer { get; set; } // Referer (Primary key) (length: 150)

        [Column(@"IsRead", Order = 16, TypeName = "tinyint")]
        [Display(Name = "Is read")]
        public byte? IsRead { get; set; } // IsRead

        [Column(@"IsDeleted", Order = 17, TypeName = "tinyint")]
        [Display(Name = "Is deleted")]
        public byte? IsDeleted { get; set; } // IsDeleted

        [Column(@"AdminBlock", Order = 18, TypeName = "tinyint")]
        [Display(Name = "Admin block")]
        public byte? AdminBlock { get; set; } // AdminBlock

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ISCoverLetterIncluded", Order = 19, TypeName = "tinyint")]
        [Required]
        [Key]
        [Display(Name = "Isc over letter included")]
        public byte IsCoverLetterIncluded { get; set; } // ISCoverLetterIncluded (Primary key)

        [Column(@"QuestionAnswerXML", Order = 20, TypeName = "varchar(max)")]
        [Display(Name = "Question answer xml")]
        public string QuestionAnswerXml { get; set; } // QuestionAnswerXML

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UpdatedBy", Order = 21, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CreatedBy", Order = 22, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DateAdded", Order = 23, TypeName = "datetime")]
        [Required]
        [Key]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DateUpdated", Order = 24, TypeName = "datetime")]
        [Required]
        [Key]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated (Primary key)
    }

}
// </auto-generated>
