// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository;
    using entityframeworkrepository.core.entity;
    using Newtonsoft.Json;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    // JobFormResultQA
    [Table("JobFormResultQA", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class JobFormResultQa: BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"JobFormResultQAID", Order = 1, TypeName = "int")]
        [Index(@"PK_JobFormResultQA", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Job form result qaid")]
        public int JobFormResultQaid { get; set; } // JobFormResultQAID (Primary key)

        [Column(@"JobFormResultID", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Job form result ID")]
        public int JobFormResultId { get; set; } // JobFormResultID

        [Column(@"CandidateID", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Candidate ID")]
        public int CandidateId { get; set; } // CandidateID

        [Column(@"QuestionAnswerXML", Order = 4, TypeName = "varchar(max)")]
        [Display(Name = "Question answer xml")]
        public string QuestionAnswerXml { get; set; } // QuestionAnswerXML

        [Column(@"UpdatedBy", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        [Column(@"Question", Order = 9, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Question")]
        public string Question { get; set; } // Question (length: 50)

        [Column(@"QuestionUniqueID", Order = 10, TypeName = "varchar")]
        [MaxLength(36)]
        [StringLength(36)]
        [Display(Name = "Question unique ID")]
        public string QuestionUniqueId { get; set; } // QuestionUniqueID (length: 36)

        [Column(@"QuestionWeight", Order = 11, TypeName = "int")]
        [Display(Name = "Question weight")]
        public System.Nullable<int> QuestionWeight { get; set; } // QuestionWeight

        [Column(@"IsAnswer", Order = 12, TypeName = "bit")]
        [Display(Name = "Is answer")]
        public System.Nullable<bool> IsAnswer { get; set; } // IsAnswer

        public JobFormResultQa()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
