// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    // JobFormResultsView
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class JobFormResultsViewConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<JobFormResultsView>
    {
        public JobFormResultsViewConfiguration()
            : this("dbo")
        {
        }

        public JobFormResultsViewConfiguration(string schema)
        {
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.JobFormId).IsOptional();
            Property(x => x.CvBankFilename).IsOptional().IsUnicode(false);
            Property(x => x.ApplicantName).IsOptional().IsUnicode(false);
            Property(x => x.CandidateId).IsOptional();
            Property(x => x.ApplicantFakeName).IsOptional().IsUnicode(false);
            Property(x => x.DateApplied).IsOptional();
            Property(x => x.JobTitle).IsOptional().IsUnicode(false);
            Property(x => x.JobDescription).IsOptional().IsUnicode(false);
            Property(x => x.JobPostedName).IsOptional().IsUnicode(false);
            Property(x => x.JobUpdatedByName).IsOptional().IsUnicode(false);
            Property(x => x.CompanyName).IsUnicode(false);
            Property(x => x.Department).IsUnicode(false);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
