// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // Pipeline
    [Table("Pipeline", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class Pipeline
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"PipelineID", Order = 1, TypeName = "int")]
        [Index(@"PK_Pipeline", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Pipeline ID")]
        public int PipelineId { get; set; } // PipelineID (Primary key)

        [Column(@"StageID", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Stage ID")]
        public int StageId { get; set; } // StageID

        [Column(@"CandidateID", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Candidate ID")]
        public int CandidateId { get; set; } // CandidateID

        [Column(@"JobID", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Job ID")]
        public int JobId { get; set; } // JobID

        [Column(@"UpdatedBy", Order = 5, TypeName = "int")]
        [Display(Name = "Updated by")]
        public int? UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        [Column(@"IsDeclined", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Is declined")]
        public bool IsDeclined { get; set; } // IsDeclined

        // Foreign keys
        [ForeignKey("StageId")] public virtual Stage Stage { get; set; } // FK_Pipeline_Stage
    }

}
// </auto-generated>
