// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // SharedContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class SharedContentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SharedContent>
    {
        public SharedContentConfiguration()
            : this("dbo")
        {
        }

        public SharedContentConfiguration(string schema)
        {
            Property(x => x.JobFormResultId).IsOptional();
            Property(x => x.ShareContentTypeId).IsOptional();
            Property(x => x.AllowComment).IsOptional();
            Property(x => x.ShowTimeLineEvaluation).IsOptional();
            Property(x => x.ShareContentMessage).IsOptional().IsUnicode(false);
            Property(x => x.ShareContentLink).IsOptional().IsUnicode(false);
            Property(x => x.ShareContentWith).IsOptional();
            Property(x => x.ShareContentWithEmail).IsOptional().IsUnicode(false);
        }
    }

}
// </auto-generated>
