// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using System.ComponentModel.DataAnnotations;

    // Stage
    [Table("Stage", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public class Stage
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"StageID", Order = 1, TypeName = "int")]
        [Index(@"PK_Stage", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Stage ID")]
        public int StageId { get; set; } // StageID (Primary key)

        [Column(@"ID", Order = 2, TypeName = "int")]
        [Display(Name = "Id")]
        public int? Id { get; set; } // ID

        [Column(@"JobFormResultID", Order = 3, TypeName = "int")]
        [Display(Name = "Job form result ID")]
        public int? JobFormResultId { get; set; } // JobFormResultID

        [Column(@"NewsStageName", Order = 4, TypeName = "varchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "News stage name")]
        public string NewsStageName { get; set; } // NewsStageName (length: 20)

        [Column(@"DepartmentID", Order = 5, TypeName = "int")]
        [Display(Name = "Department ID")]
        public int? DepartmentId { get; set; } // DepartmentID

        [Column(@"UpdatedBy", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Pipeline> Pipelines { get; set; } // Pipeline.FK_Pipeline_Stage

        public Stage()
        {
            Pipelines = new System.Collections.Generic.List<Pipeline>();
        }
    }

}
// </auto-generated>
