// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using System.ComponentModel.DataAnnotations;

    // Template
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class TemplateConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Template>
    {
        public TemplateConfiguration()
            : this("dbo")
        {
        }

        public TemplateConfiguration(string schema)
        {
            Property(x => x.TemplateName).IsOptional().IsUnicode(false);
            Property(x => x.TemplateText).IsOptional().IsUnicode(false);
            Property(x => x.TemplateAttachment).IsOptional().IsUnicode(false);
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.SortOrder).IsOptional();
            Property(x => x.CompanyId).IsOptional();
            Property(x => x.DepartmentId).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
