// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    // Template
    [Table("Template", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Template: BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"TemplateID", Order = 1, TypeName = "int")]
        [Index(@"PK_Template", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Template ID")]
        public int TemplateId { get; set; } // TemplateID (Primary key)

        [Column(@"TemplateName", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Template name")]
        public string TemplateName { get; set; } // TemplateName (length: 50)

        [Column(@"TemplateText", Order = 3, TypeName = "varchar(max)")]
        [Display(Name = "Template text")]
        public string TemplateText { get; set; } // TemplateText

        [Column(@"TemplateAttachment", Order = 4, TypeName = "varchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Template attachment")]
        public string TemplateAttachment { get; set; } // TemplateAttachment (length: 100)

        [Column(@"IsDeleted", Order = 5, TypeName = "tinyint")]
        [Display(Name = "Is deleted")]
        public byte? IsDeleted { get; set; } // IsDeleted

        [Column(@"SortOrder", Order = 6, TypeName = "int")]
        [Display(Name = "Sort order")]
        public int? SortOrder { get; set; } // SortOrder

        [Column(@"CompanyID", Order = 7, TypeName = "int")]
        [Display(Name = "Company ID")]
        public int? CompanyId { get; set; } // CompanyID

        [Column(@"DepartmentID", Order = 8, TypeName = "int")]
        [Display(Name = "Department ID")]
        public int? DepartmentId { get; set; } // DepartmentID

        [Column(@"UpdatedBy", Order = 9, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 10, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date added")]
        public System.DateTime DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 12, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        // Foreign keys
        [JsonIgnore]
        [ForeignKey("CreatedBy")] public virtual Person Person_CreatedBy { get; set; } // FK_Template_Person
        [JsonIgnore]
        [ForeignKey("UpdatedBy")] public virtual Person Person_UpdatedBy { get; set; } // FK_Template_Person2

        public Template()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
