// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace entityframeworkrepository
{
    using entityframeworkrepository.core;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    // TokenManager
    [Table("TokenManager", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class TokenManager: BaseEntity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"TokenId", Order = 1, TypeName = "int")]
        [Index(@"PK_[TokenManager", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Token ID")]
        public int TokenId { get; set; } // TokenId (Primary key)

        [Column(@"Token", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Token")]
        public string Token { get; set; } // Token (length: 50)

        [Column(@"Email", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 50)

        [Column(@"IPAddress", Order = 4, TypeName = "varchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Ipa ddress")]
        public string IpAddress { get; set; } // IPAddress (length: 20)

        [Column(@"TypeId", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Type ID")]
        public int TypeId { get; set; } // TypeId

        [Column(@"UpdatedBy", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Updated by")]
        public int UpdatedBy { get; set; } // UpdatedBy

        [Column(@"CreatedBy", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        [Column(@"DateAdded", Order = 8, TypeName = "datetime")]
        [Display(Name = "Date added")]
        public System.DateTime? DateAdded { get; set; } // DateAdded

        [Column(@"DateUpdated", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Date updated")]
        public System.DateTime DateUpdated { get; set; } // DateUpdated

        public TokenManager()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
